In [554]:
import pandas as pd
import numpy as np

In [555]:
df= pd.read_csv("./Engr_371_Data.csv")

In [556]:
df

,Timestamp,Are you currently a student at Concordia University?,What program are you in?,What is your current GPA?,Are you currently in a CO-OP program for your degree?,Have you ever completed an internship related to your program?,How many internships have you completed related to your program?,How have you obtained any of your internships?,Are you currently looking for an internship?,Are you currently looking for an internship or have in the past looked for an internship?,"Being in CO-OP, are you in the process or have you completed an internship related to your program?","Being in CO-OP, how do you go about finding an internship opportunity?",Which of the following describe how you've been searching for internships?,Have you ever gotten to an interview stage in the process of applying to an internship,If so how many interviews have you done in the process of applying for an internship,How often do you practice your program's material outside class related assignments? (In hours per week),"If you use it, how many connections do you have on LinkedIn?"
0,11/29/2024 0:05:02,Yes,Software Engineering,3.5-4.0,No,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,0-3,< 200
1,11/29/2024 1:20:10,Yes,Aerospace Engineering,2.5-2.9,No,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,0-3,< 200
2,11/29/2024 1:42:10,Yes,Computer Engineering,3.0-3.49,Yes,NaN,NaN,NaN,NaN,NaN,No,Applications to job postings,NaN,NaN,NaN,8-10,< 200
3,11/29/2024 14:42:19,Yes,Accounting,3.5-4.0,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,5,16-20,> 700
4,11/29/2024 16:11:06,Yes,Aerospace engineering,> 4.0,Yes,NaN,NaN,NaN,NaN,NaN,Yes,"Personal connections (teachers, relatives, col...",NaN,NaN,NaN,16-20,300-399
5,11/29/2024 18:21:44,Yes,Mechanical Engineering,2.5-2.9,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",No,0,4-7,< 200
6,11/30/2024 13:46:41,Yes,Software Engineering,3.5-4.0,No,Yes,1.0,"Personal connections (teachers, relatives, col...",Yes,NaN,NaN,NaN,"Personal connections (teachers, relatives, col...",No,0,4-7,500-599
7,11/30/2024 13:49:25,Yes,Software Engineering,3.5-4.0,Yes,NaN,NaN,NaN,NaN,NaN,Yes,"Personal connections (teachers, relatives, col...",NaN,NaN,NaN,4-7,< 200
8,11/30/2024 13:52:06,Yes,Software Engineering,3.5-4.0,Yes,NaN,2.0,The university aided me in obtaining the inter...,No,NaN,Yes,The university aided me in obtaining the inter...,NaN,NaN,NaN,8-10,400-499
9,11/30/2024 13:53:01,Yes,Sociology,3.0-3.49,No,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,0-3,0
10,11/30/2024 13:57:42,Yes,Mechanical Engineering,3.0-3.49,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,1,0-3,< 200
11,11/30/2024 13:59:01,Yes,Software Engineering,3.0-3.49,No,No,NaN,NaN,NaN,Yes,NaN,NaN,Doing research,No,0,4-7,500-599
12,11/30/2024 14:01:40,Yes,Computer Science,3.5-4.0,No,Yes,1.0,"Personal connections (teachers, relatives, col...",No,NaN,NaN,NaN,NaN,NaN,NaN,11-15,200-299
13,11/30/2024 14:03:16,Yes,Software Engineering,3.5-4.0,No,Yes,1.0,"Personal connections (teachers, relatives, col...",Yes,NaN,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,2,11-15,300-399
14,11/30/2024 14:05:38,Yes,HR,3.0-3.49,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,1,4-7,< 200
15,11/30/2024 14:08:09,Yes,ECEE,3.5-4.0,No,Yes,2.0,The university aided me in obtaining the inter...,No,NaN,NaN,NaN,NaN,NaN,NaN,8-10,0
16,11/30/2024 14:10:22,Yes,Sociology,3.5-4.0,No,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,11-15,0
17,11/30/2024 14:12:03,Yes,Psychology,3.0-3.49,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",No,0,0-3,0
18,11/30/2024 14:12:59,Yes,Engineering,3.5-4.0,No,No,NaN,NaN,NaN,Yes,NaN,NaN,Applying to job postings,Yes,1,0-3,0
19,11/30/2024 14:14:11,Yes,Soci,2.5-2.9,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",No,0,8-10,< 200
20,11/30/2024 14:15:40,Yes,Software Engineering,> 4.0,Yes,NaN,4.0,The university aided me in obtaining the inter...,Yes,NaN,Yes,The university aided me in obtaining the inter...,"Personal connections (teachers, relatives, col...",Yes,> 6,0-3,0
21,11/30/2024 14:16:06,Yes,Software Engineering,2.5-2.9,No,Yes,2.0,The university aided me in obtaining the inter...,Yes,NaN,NaN,NaN,Applying to job postings,Yes,> 6,0-3,400-499
22,11/30/2024 14:21:55,Yes,Accounting,3.0-3.49,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,1,20+,> 700
23,11/30/2024 14:22:19,Yes,Computer Science,3.0-3.49,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Applying to job postings, Networking events",Yes,2,0-3,< 200
24,11/30/2024 14:25:50,Yes,Aerospace Engineering,3.5-4.0,Yes,NaN,2.0,The university aided me in obtaining the inter...,No,NaN,Yes,The university aided me in obtaining the inter...,NaN,NaN,NaN,20+,200-299
25,11/30/2024 14:26:27,Yes,Accounting,3.5-4.0,No,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,16-20,> 700
26,11/30/2024 14:27:54,Yes,Accounting,2.5-2.9,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",No,0,8-10,< 200
27,11/30/2024 14:28:43,Yes,Accounting,3.0-3.49,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",No,0,4-7,0
28,11/30/2024 14:29:19,Yes,Bcomm,3.0-3.49,No,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,0-3,600-699
29,11/30/2024 14:30:14,Yes,Bcom,3.5-4.0,No,Yes,1.0,"Personal connections (teachers, relatives, col...",Yes,NaN,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,1,4-7,200-299
30,11/30/2024 14:31:16,Yes,Accounting,> 4.0,No,Yes,1.0,Applications to job postings,No,NaN,NaN,NaN,NaN,NaN,NaN,20+,< 200
31,11/30/2024 14:32:56,Yes,BUSINESS - MAJOR IN SUPPLY CHAIN AND MANAGEMENT,3.0-3.49,Yes,NaN,3.0,The university aided me in obtaining the inter...,No,NaN,Yes,The university aided me in obtaining the inter...,NaN,NaN,NaN,8-10,0
32,11/30/2024 14:34:10,Yes,Marketing,3.5-4.0,No,Yes,3.0,"Personal connections (teachers, relatives, col...",No,NaN,NaN,NaN,NaN,NaN,NaN,4-7,600-699
33,11/30/2024 14:34:47,Yes,Accounting,3.5-4.0,No,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,8-10,< 200
34,11/30/2024 14:35:35,Yes,Finance,2.5-2.9,No,No,NaN,NaN,NaN,Yes,NaN,NaN,I have not yet began my search,No,0,11-15,< 200
35,11/30/2024 14:36:07,Yes,Software Engineering,3.5-4.0,No,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,0-3,< 200
36,11/30/2024 17:46:54,Yes,Software engineering,3.0-3.49,Yes,NaN,2.0,The university aided me in obtaining the inter...,No,NaN,Yes,The university aided me in obtaining the inter...,NaN,NaN,NaN,0-3,500-599
37,11/30/2024 18:38:33,Yes,Computer Engineering,3.0-3.49,Yes,NaN,NaN,NaN,NaN,NaN,No,The university aided me in obtaining the inter...,"Personal connections (teachers, relatives, col...",Yes,3,4-7,200-299
38,11/30/2024 19:24:25,Yes,Computer Science,3.0-3.49,Yes,NaN,0.0,The university aided me in obtaining the inter...,No,NaN,Yes,The university aided me in obtaining the inter...,NaN,NaN,NaN,0-3,300-399
39,12/1/2024 11:06:19,Yes,finance,2.5-2.9,No,Yes,1.0,"Personal connections (teachers, relatives, col...",Yes,NaN,NaN,NaN,"Personal connections (teachers, relatives, col...",No,2,8-10,< 200
40,12/1/2024 11:06:25,Yes,Finance,3.0-3.49,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Applying to job postings, Networking events",Yes,4,8-10,< 200
41,12/1/2024 11:06:49,Yes,Accounting,3.0-3.49,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Applying to job postings, Networking events",Yes,4,11-15,< 200
42,12/1/2024 11:07:07,Yes,HRM,2.5-2.9,No,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,0-3,< 200
43,12/1/2024 11:07:21,Yes,accounting,3.0-3.49,No,No,NaN,NaN,NaN,Yes,NaN,NaN,Networking events,Yes,2,11-15,< 200
44,12/1/2024 11:07:29,Yes,IBUS,3.0-3.49,Yes,NaN,2.0,The university aided me in obtaining the inter...,Yes,NaN,Yes,Applications to job postings,"Applying to job postings, Networking events",Yes,4,0-3,< 200
45,12/1/2024 11:08:07,Yes,Finance,3.5-4.0,No,Yes,2.0,Applications to job postings,Yes,NaN,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,> 6,11-15,200-299
46,12/1/2024 11:08:18,Yes,Marketing,3.5-4.0,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,2,4-7,< 200
47,12/1/2024 11:08:40,Yes,Marketing,3.0-3.49,Yes,NaN,3.0,The university aided me in obtaining the inter...,No,NaN,Yes,The university aided me in obtaining the inter...,NaN,NaN,NaN,0-3,< 200
48,12/1/2024 11:09:17,Yes,Management,3.0-3.49,No,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,8-10,0
49,12/1/2024 11:10:06,Yes,Accounting,2.0-2.49,No,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,8-10,< 200
50,12/1/2024 11:10:48,Yes,BAdmin,2.5-2.9,No,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,0-3,0
51,12/1/2024 11:13:58,Yes,BTM,2.5-2.9,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,2,4-7,< 200
52,12/1/2024 11:19:50,Yes,BTM,3.0-3.49,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Applying to job postings, Networking events",No,0,0-3,< 200
53,12/1/2024 13:13:55,Yes,Certificate in Accountancy,3.5-4.0,No,Yes,3.0,Applications to job postings,No,NaN,NaN,NaN,NaN,NaN,NaN,0-3,200-299
54,12/1/2024 13:57:02,Yes,Accounting,3.5-4.0,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Applying to job postings, Networking events",No,0,0-3,< 200

In [557]:
df =df.drop(columns  = "Timestamp")

In [558]:
df = df[df['Are you currently a student at Concordia University?'] != 'No']

In [559]:
df= df.drop(columns = 'Are you currently a student at Concordia University?')

In [560]:
df

,What program are you in?,What is your current GPA?,Are you currently in a CO-OP program for your degree?,Have you ever completed an internship related to your program?,How many internships have you completed related to your program?,How have you obtained any of your internships?,Are you currently looking for an internship?,Are you currently looking for an internship or have in the past looked for an internship?,"Being in CO-OP, are you in the process or have you completed an internship related to your program?","Being in CO-OP, how do you go about finding an internship opportunity?",Which of the following describe how you've been searching for internships?,Have you ever gotten to an interview stage in the process of applying to an internship,If so how many interviews have you done in the process of applying for an internship,How often do you practice your program's material outside class related assignments? (In hours per week),"If you use it, how many connections do you have on LinkedIn?"
0,Software Engineering,3.5-4.0,No,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,0-3,< 200
1,Aerospace Engineering,2.5-2.9,No,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,0-3,< 200
2,Computer Engineering,3.0-3.49,Yes,NaN,NaN,NaN,NaN,NaN,No,Applications to job postings,NaN,NaN,NaN,8-10,< 200
3,Accounting,3.5-4.0,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,5,16-20,> 700
4,Aerospace engineering,> 4.0,Yes,NaN,NaN,NaN,NaN,NaN,Yes,"Personal connections (teachers, relatives, col...",NaN,NaN,NaN,16-20,300-399
5,Mechanical Engineering,2.5-2.9,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",No,0,4-7,< 200
6,Software Engineering,3.5-4.0,No,Yes,1.0,"Personal connections (teachers, relatives, col...",Yes,NaN,NaN,NaN,"Personal connections (teachers, relatives, col...",No,0,4-7,500-599
7,Software Engineering,3.5-4.0,Yes,NaN,NaN,NaN,NaN,NaN,Yes,"Personal connections (teachers, relatives, col...",NaN,NaN,NaN,4-7,< 200
8,Software Engineering,3.5-4.0,Yes,NaN,2.0,The university aided me in obtaining the inter...,No,NaN,Yes,The university aided me in obtaining the inter...,NaN,NaN,NaN,8-10,400-499
9,Sociology,3.0-3.49,No,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,0-3,0
10,Mechanical Engineering,3.0-3.49,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,1,0-3,< 200
11,Software Engineering,3.0-3.49,No,No,NaN,NaN,NaN,Yes,NaN,NaN,Doing research,No,0,4-7,500-599
12,Computer Science,3.5-4.0,No,Yes,1.0,"Personal connections (teachers, relatives, col...",No,NaN,NaN,NaN,NaN,NaN,NaN,11-15,200-299
13,Software Engineering,3.5-4.0,No,Yes,1.0,"Personal connections (teachers, relatives, col...",Yes,NaN,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,2,11-15,300-399
14,HR,3.0-3.49,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,1,4-7,< 200
15,ECEE,3.5-4.0,No,Yes,2.0,The university aided me in obtaining the inter...,No,NaN,NaN,NaN,NaN,NaN,NaN,8-10,0
16,Sociology,3.5-4.0,No,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,11-15,0
17,Psychology,3.0-3.49,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",No,0,0-3,0
18,Engineering,3.5-4.0,No,No,NaN,NaN,NaN,Yes,NaN,NaN,Applying to job postings,Yes,1,0-3,0
19,Soci,2.5-2.9,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",No,0,8-10,< 200
20,Software Engineering,> 4.0,Yes,NaN,4.0,The university aided me in obtaining the inter...,Yes,NaN,Yes,The university aided me in obtaining the inter...,"Personal connections (teachers, relatives, col...",Yes,> 6,0-3,0
21,Software Engineering,2.5-2.9,No,Yes,2.0,The university aided me in obtaining the inter...,Yes,NaN,NaN,NaN,Applying to job postings,Yes,> 6,0-3,400-499
22,Accounting,3.0-3.49,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,1,20+,> 700
23,Computer Science,3.0-3.49,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Applying to job postings, Networking events",Yes,2,0-3,< 200
24,Aerospace Engineering,3.5-4.0,Yes,NaN,2.0,The university aided me in obtaining the inter...,No,NaN,Yes,The university aided me in obtaining the inter...,NaN,NaN,NaN,20+,200-299
25,Accounting,3.5-4.0,No,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,16-20,> 700
26,Accounting,2.5-2.9,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",No,0,8-10,< 200
27,Accounting,3.0-3.49,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",No,0,4-7,0
28,Bcomm,3.0-3.49,No,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,0-3,600-699
29,Bcom,3.5-4.0,No,Yes,1.0,"Personal connections (teachers, relatives, col...",Yes,NaN,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,1,4-7,200-299
30,Accounting,> 4.0,No,Yes,1.0,Applications to job postings,No,NaN,NaN,NaN,NaN,NaN,NaN,20+,< 200
31,BUSINESS - MAJOR IN SUPPLY CHAIN AND MANAGEMENT,3.0-3.49,Yes,NaN,3.0,The university aided me in obtaining the inter...,No,NaN,Yes,The university aided me in obtaining the inter...,NaN,NaN,NaN,8-10,0
32,Marketing,3.5-4.0,No,Yes,3.0,"Personal connections (teachers, relatives, col...",No,NaN,NaN,NaN,NaN,NaN,NaN,4-7,600-699
33,Accounting,3.5-4.0,No,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,8-10,< 200
34,Finance,2.5-2.9,No,No,NaN,NaN,NaN,Yes,NaN,NaN,I have not yet began my search,No,0,11-15,< 200
35,Software Engineering,3.5-4.0,No,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,0-3,< 200
36,Software engineering,3.0-3.49,Yes,NaN,2.0,The university aided me in obtaining the inter...,No,NaN,Yes,The university aided me in obtaining the inter...,NaN,NaN,NaN,0-3,500-599
37,Computer Engineering,3.0-3.49,Yes,NaN,NaN,NaN,NaN,NaN,No,The university aided me in obtaining the inter...,"Personal connections (teachers, relatives, col...",Yes,3,4-7,200-299
38,Computer Science,3.0-3.49,Yes,NaN,0.0,The university aided me in obtaining the inter...,No,NaN,Yes,The university aided me in obtaining the inter...,NaN,NaN,NaN,0-3,300-399
39,finance,2.5-2.9,No,Yes,1.0,"Personal connections (teachers, relatives, col...",Yes,NaN,NaN,NaN,"Personal connections (teachers, relatives, col...",No,2,8-10,< 200
40,Finance,3.0-3.49,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Applying to job postings, Networking events",Yes,4,8-10,< 200
41,Accounting,3.0-3.49,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Applying to job postings, Networking events",Yes,4,11-15,< 200
42,HRM,2.5-2.9,No,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,0-3,< 200
43,accounting,3.0-3.49,No,No,NaN,NaN,NaN,Yes,NaN,NaN,Networking events,Yes,2,11-15,< 200
44,IBUS,3.0-3.49,Yes,NaN,2.0,The university aided me in obtaining the inter...,Yes,NaN,Yes,Applications to job postings,"Applying to job postings, Networking events",Yes,4,0-3,< 200
45,Finance,3.5-4.0,No,Yes,2.0,Applications to job postings,Yes,NaN,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,> 6,11-15,200-299
46,Marketing,3.5-4.0,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,2,4-7,< 200
47,Marketing,3.0-3.49,Yes,NaN,3.0,The university aided me in obtaining the inter...,No,NaN,Yes,The university aided me in obtaining the inter...,NaN,NaN,NaN,0-3,< 200
48,Management,3.0-3.49,No,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,8-10,0
49,Accounting,2.0-2.49,No,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,8-10,< 200
50,BAdmin,2.5-2.9,No,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,0-3,0
51,BTM,2.5-2.9,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,2,4-7,< 200
52,BTM,3.0-3.49,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Applying to job postings, Networking events",No,0,0-3,< 200
53,Certificate in Accountancy,3.5-4.0,No,Yes,3.0,Applications to job postings,No,NaN,NaN,NaN,NaN,NaN,NaN,0-3,200-299
54,Accounting,3.5-4.0,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Applying to job postings, Networking events",No,0,0-3,< 200

In [561]:
df = df.drop(columns = 'What program are you in?')

In [562]:
df

,What is your current GPA?,Are you currently in a CO-OP program for your degree?,Have you ever completed an internship related to your program?,How many internships have you completed related to your program?,How have you obtained any of your internships?,Are you currently looking for an internship?,Are you currently looking for an internship or have in the past looked for an internship?,"Being in CO-OP, are you in the process or have you completed an internship related to your program?","Being in CO-OP, how do you go about finding an internship opportunity?",Which of the following describe how you've been searching for internships?,Have you ever gotten to an interview stage in the process of applying to an internship,If so how many interviews have you done in the process of applying for an internship,How often do you practice your program's material outside class related assignments? (In hours per week),"If you use it, how many connections do you have on LinkedIn?"
0,3.5-4.0,No,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,0-3,< 200
1,2.5-2.9,No,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,0-3,< 200
2,3.0-3.49,Yes,NaN,NaN,NaN,NaN,NaN,No,Applications to job postings,NaN,NaN,NaN,8-10,< 200
3,3.5-4.0,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,5,16-20,> 700
4,> 4.0,Yes,NaN,NaN,NaN,NaN,NaN,Yes,"Personal connections (teachers, relatives, col...",NaN,NaN,NaN,16-20,300-399
5,2.5-2.9,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",No,0,4-7,< 200
6,3.5-4.0,No,Yes,1.0,"Personal connections (teachers, relatives, col...",Yes,NaN,NaN,NaN,"Personal connections (teachers, relatives, col...",No,0,4-7,500-599
7,3.5-4.0,Yes,NaN,NaN,NaN,NaN,NaN,Yes,"Personal connections (teachers, relatives, col...",NaN,NaN,NaN,4-7,< 200
8,3.5-4.0,Yes,NaN,2.0,The university aided me in obtaining the inter...,No,NaN,Yes,The university aided me in obtaining the inter...,NaN,NaN,NaN,8-10,400-499
9,3.0-3.49,No,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,0-3,0
10,3.0-3.49,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,1,0-3,< 200
11,3.0-3.49,No,No,NaN,NaN,NaN,Yes,NaN,NaN,Doing research,No,0,4-7,500-599
12,3.5-4.0,No,Yes,1.0,"Personal connections (teachers, relatives, col...",No,NaN,NaN,NaN,NaN,NaN,NaN,11-15,200-299
13,3.5-4.0,No,Yes,1.0,"Personal connections (teachers, relatives, col...",Yes,NaN,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,2,11-15,300-399
14,3.0-3.49,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,1,4-7,< 200
15,3.5-4.0,No,Yes,2.0,The university aided me in obtaining the inter...,No,NaN,NaN,NaN,NaN,NaN,NaN,8-10,0
16,3.5-4.0,No,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,11-15,0
17,3.0-3.49,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",No,0,0-3,0
18,3.5-4.0,No,No,NaN,NaN,NaN,Yes,NaN,NaN,Applying to job postings,Yes,1,0-3,0
19,2.5-2.9,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",No,0,8-10,< 200
20,> 4.0,Yes,NaN,4.0,The university aided me in obtaining the inter...,Yes,NaN,Yes,The university aided me in obtaining the inter...,"Personal connections (teachers, relatives, col...",Yes,> 6,0-3,0
21,2.5-2.9,No,Yes,2.0,The university aided me in obtaining the inter...,Yes,NaN,NaN,NaN,Applying to job postings,Yes,> 6,0-3,400-499
22,3.0-3.49,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,1,20+,> 700
23,3.0-3.49,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Applying to job postings, Networking events",Yes,2,0-3,< 200
24,3.5-4.0,Yes,NaN,2.0,The university aided me in obtaining the inter...,No,NaN,Yes,The university aided me in obtaining the inter...,NaN,NaN,NaN,20+,200-299
25,3.5-4.0,No,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,16-20,> 700
26,2.5-2.9,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",No,0,8-10,< 200
27,3.0-3.49,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",No,0,4-7,0
28,3.0-3.49,No,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,0-3,600-699
29,3.5-4.0,No,Yes,1.0,"Personal connections (teachers, relatives, col...",Yes,NaN,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,1,4-7,200-299
30,> 4.0,No,Yes,1.0,Applications to job postings,No,NaN,NaN,NaN,NaN,NaN,NaN,20+,< 200
31,3.0-3.49,Yes,NaN,3.0,The university aided me in obtaining the inter...,No,NaN,Yes,The university aided me in obtaining the inter...,NaN,NaN,NaN,8-10,0
32,3.5-4.0,No,Yes,3.0,"Personal connections (teachers, relatives, col...",No,NaN,NaN,NaN,NaN,NaN,NaN,4-7,600-699
33,3.5-4.0,No,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,8-10,< 200
34,2.5-2.9,No,No,NaN,NaN,NaN,Yes,NaN,NaN,I have not yet began my search,No,0,11-15,< 200
35,3.5-4.0,No,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,0-3,< 200
36,3.0-3.49,Yes,NaN,2.0,The university aided me in obtaining the inter...,No,NaN,Yes,The university aided me in obtaining the inter...,NaN,NaN,NaN,0-3,500-599
37,3.0-3.49,Yes,NaN,NaN,NaN,NaN,NaN,No,The university aided me in obtaining the inter...,"Personal connections (teachers, relatives, col...",Yes,3,4-7,200-299
38,3.0-3.49,Yes,NaN,0.0,The university aided me in obtaining the inter...,No,NaN,Yes,The university aided me in obtaining the inter...,NaN,NaN,NaN,0-3,300-399
39,2.5-2.9,No,Yes,1.0,"Personal connections (teachers, relatives, col...",Yes,NaN,NaN,NaN,"Personal connections (teachers, relatives, col...",No,2,8-10,< 200
40,3.0-3.49,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Applying to job postings, Networking events",Yes,4,8-10,< 200
41,3.0-3.49,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Applying to job postings, Networking events",Yes,4,11-15,< 200
42,2.5-2.9,No,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,0-3,< 200
43,3.0-3.49,No,No,NaN,NaN,NaN,Yes,NaN,NaN,Networking events,Yes,2,11-15,< 200
44,3.0-3.49,Yes,NaN,2.0,The university aided me in obtaining the inter...,Yes,NaN,Yes,Applications to job postings,"Applying to job postings, Networking events",Yes,4,0-3,< 200
45,3.5-4.0,No,Yes,2.0,Applications to job postings,Yes,NaN,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,> 6,11-15,200-299
46,3.5-4.0,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,2,4-7,< 200
47,3.0-3.49,Yes,NaN,3.0,The university aided me in obtaining the inter...,No,NaN,Yes,The university aided me in obtaining the inter...,NaN,NaN,NaN,0-3,< 200
48,3.0-3.49,No,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,8-10,0
49,2.0-2.49,No,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,8-10,< 200
50,2.5-2.9,No,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,0-3,0
51,2.5-2.9,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,2,4-7,< 200
52,3.0-3.49,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Applying to job postings, Networking events",No,0,0-3,< 200
53,3.5-4.0,No,Yes,3.0,Applications to job postings,No,NaN,NaN,NaN,NaN,NaN,NaN,0-3,200-299
54,3.5-4.0,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Applying to job postings, Networking events",No,0,0-3,< 200

In [563]:
gpa_mapping = {
    '< 2.0': 1.0,
    '2.0-2.49': 2.25,
    '2.5-2.9': 2.7,
    '3.0-3.49': 3.25,
    '3.5-4.0': 3.75,
    '> 4.0': 4.1
}
df['GPA Midpoint'] = df['What is your current GPA?'].map(gpa_mapping)
df = df.drop(columns = 'What is your current GPA?')

In [564]:
df

,Are you currently in a CO-OP program for your degree?,Have you ever completed an internship related to your program?,How many internships have you completed related to your program?,How have you obtained any of your internships?,Are you currently looking for an internship?,Are you currently looking for an internship or have in the past looked for an internship?,"Being in CO-OP, are you in the process or have you completed an internship related to your program?","Being in CO-OP, how do you go about finding an internship opportunity?",Which of the following describe how you've been searching for internships?,Have you ever gotten to an interview stage in the process of applying to an internship,If so how many interviews have you done in the process of applying for an internship,How often do you practice your program's material outside class related assignments? (In hours per week),"If you use it, how many connections do you have on LinkedIn?",GPA Midpoint
0,No,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,0-3,< 200,3.75
1,No,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,0-3,< 200,2.70
2,Yes,NaN,NaN,NaN,NaN,NaN,No,Applications to job postings,NaN,NaN,NaN,8-10,< 200,3.25
3,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,5,16-20,> 700,3.75
4,Yes,NaN,NaN,NaN,NaN,NaN,Yes,"Personal connections (teachers, relatives, col...",NaN,NaN,NaN,16-20,300-399,4.10
5,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",No,0,4-7,< 200,2.70
6,No,Yes,1.0,"Personal connections (teachers, relatives, col...",Yes,NaN,NaN,NaN,"Personal connections (teachers, relatives, col...",No,0,4-7,500-599,3.75
7,Yes,NaN,NaN,NaN,NaN,NaN,Yes,"Personal connections (teachers, relatives, col...",NaN,NaN,NaN,4-7,< 200,3.75
8,Yes,NaN,2.0,The university aided me in obtaining the inter...,No,NaN,Yes,The university aided me in obtaining the inter...,NaN,NaN,NaN,8-10,400-499,3.75
9,No,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,0-3,0,3.25
10,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,1,0-3,< 200,3.25
11,No,No,NaN,NaN,NaN,Yes,NaN,NaN,Doing research,No,0,4-7,500-599,3.25
12,No,Yes,1.0,"Personal connections (teachers, relatives, col...",No,NaN,NaN,NaN,NaN,NaN,NaN,11-15,200-299,3.75
13,No,Yes,1.0,"Personal connections (teachers, relatives, col...",Yes,NaN,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,2,11-15,300-399,3.75
14,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,1,4-7,< 200,3.25
15,No,Yes,2.0,The university aided me in obtaining the inter...,No,NaN,NaN,NaN,NaN,NaN,NaN,8-10,0,3.75
16,No,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,11-15,0,3.75
17,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",No,0,0-3,0,3.25
18,No,No,NaN,NaN,NaN,Yes,NaN,NaN,Applying to job postings,Yes,1,0-3,0,3.75
19,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",No,0,8-10,< 200,2.70
20,Yes,NaN,4.0,The university aided me in obtaining the inter...,Yes,NaN,Yes,The university aided me in obtaining the inter...,"Personal connections (teachers, relatives, col...",Yes,> 6,0-3,0,4.10
21,No,Yes,2.0,The university aided me in obtaining the inter...,Yes,NaN,NaN,NaN,Applying to job postings,Yes,> 6,0-3,400-499,2.70
22,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,1,20+,> 700,3.25
23,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Applying to job postings, Networking events",Yes,2,0-3,< 200,3.25
24,Yes,NaN,2.0,The university aided me in obtaining the inter...,No,NaN,Yes,The university aided me in obtaining the inter...,NaN,NaN,NaN,20+,200-299,3.75
25,No,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,16-20,> 700,3.75
26,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",No,0,8-10,< 200,2.70
27,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",No,0,4-7,0,3.25
28,No,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,0-3,600-699,3.25
29,No,Yes,1.0,"Personal connections (teachers, relatives, col...",Yes,NaN,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,1,4-7,200-299,3.75
30,No,Yes,1.0,Applications to job postings,No,NaN,NaN,NaN,NaN,NaN,NaN,20+,< 200,4.10
31,Yes,NaN,3.0,The university aided me in obtaining the inter...,No,NaN,Yes,The university aided me in obtaining the inter...,NaN,NaN,NaN,8-10,0,3.25
32,No,Yes,3.0,"Personal connections (teachers, relatives, col...",No,NaN,NaN,NaN,NaN,NaN,NaN,4-7,600-699,3.75
33,No,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,8-10,< 200,3.75
34,No,No,NaN,NaN,NaN,Yes,NaN,NaN,I have not yet began my search,No,0,11-15,< 200,2.70
35,No,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,0-3,< 200,3.75
36,Yes,NaN,2.0,The university aided me in obtaining the inter...,No,NaN,Yes,The university aided me in obtaining the inter...,NaN,NaN,NaN,0-3,500-599,3.25
37,Yes,NaN,NaN,NaN,NaN,NaN,No,The university aided me in obtaining the inter...,"Personal connections (teachers, relatives, col...",Yes,3,4-7,200-299,3.25
38,Yes,NaN,0.0,The university aided me in obtaining the inter...,No,NaN,Yes,The university aided me in obtaining the inter...,NaN,NaN,NaN,0-3,300-399,3.25
39,No,Yes,1.0,"Personal connections (teachers, relatives, col...",Yes,NaN,NaN,NaN,"Personal connections (teachers, relatives, col...",No,2,8-10,< 200,2.70
40,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Applying to job postings, Networking events",Yes,4,8-10,< 200,3.25
41,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Applying to job postings, Networking events",Yes,4,11-15,< 200,3.25
42,No,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,0-3,< 200,2.70
43,No,No,NaN,NaN,NaN,Yes,NaN,NaN,Networking events,Yes,2,11-15,< 200,3.25
44,Yes,NaN,2.0,The university aided me in obtaining the inter...,Yes,NaN,Yes,Applications to job postings,"Applying to job postings, Networking events",Yes,4,0-3,< 200,3.25
45,No,Yes,2.0,Applications to job postings,Yes,NaN,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,> 6,11-15,200-299,3.75
46,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,2,4-7,< 200,3.75
47,Yes,NaN,3.0,The university aided me in obtaining the inter...,No,NaN,Yes,The university aided me in obtaining the inter...,NaN,NaN,NaN,0-3,< 200,3.25
48,No,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,8-10,0,3.25
49,No,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,8-10,< 200,2.25
50,No,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,0-3,0,2.70
51,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,2,4-7,< 200,2.70
52,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Applying to job postings, Networking events",No,0,0-3,< 200,3.25
53,No,Yes,3.0,Applications to job postings,No,NaN,NaN,NaN,NaN,NaN,NaN,0-3,200-299,3.75
54,No,No,NaN,NaN,NaN,Yes,NaN,NaN,"Applying to job postings, Networking events",No,0,0-3,< 200,3.75

In [565]:
coop_mapping = {
    'No':0,
    'Yes':1
}
df['COOP'] = df['Are you currently in a CO-OP program for your degree?'].map(coop_mapping)
df = df.drop(columns = 'Are you currently in a CO-OP program for your degree?')

In [566]:
df

,Have you ever completed an internship related to your program?,How many internships have you completed related to your program?,How have you obtained any of your internships?,Are you currently looking for an internship?,Are you currently looking for an internship or have in the past looked for an internship?,"Being in CO-OP, are you in the process or have you completed an internship related to your program?","Being in CO-OP, how do you go about finding an internship opportunity?",Which of the following describe how you've been searching for internships?,Have you ever gotten to an interview stage in the process of applying to an internship,If so how many interviews have you done in the process of applying for an internship,How often do you practice your program's material outside class related assignments? (In hours per week),"If you use it, how many connections do you have on LinkedIn?",GPA Midpoint,COOP
0,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,0-3,< 200,3.75,0
1,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,0-3,< 200,2.70,0
2,NaN,NaN,NaN,NaN,NaN,No,Applications to job postings,NaN,NaN,NaN,8-10,< 200,3.25,1
3,No,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,5,16-20,> 700,3.75,0
4,NaN,NaN,NaN,NaN,NaN,Yes,"Personal connections (teachers, relatives, col...",NaN,NaN,NaN,16-20,300-399,4.10,1
5,No,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",No,0,4-7,< 200,2.70,0
6,Yes,1.0,"Personal connections (teachers, relatives, col...",Yes,NaN,NaN,NaN,"Personal connections (teachers, relatives, col...",No,0,4-7,500-599,3.75,0
7,NaN,NaN,NaN,NaN,NaN,Yes,"Personal connections (teachers, relatives, col...",NaN,NaN,NaN,4-7,< 200,3.75,1
8,NaN,2.0,The university aided me in obtaining the inter...,No,NaN,Yes,The university aided me in obtaining the inter...,NaN,NaN,NaN,8-10,400-499,3.75,1
9,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,0-3,0,3.25,0
10,No,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,1,0-3,< 200,3.25,0
11,No,NaN,NaN,NaN,Yes,NaN,NaN,Doing research,No,0,4-7,500-599,3.25,0
12,Yes,1.0,"Personal connections (teachers, relatives, col...",No,NaN,NaN,NaN,NaN,NaN,NaN,11-15,200-299,3.75,0
13,Yes,1.0,"Personal connections (teachers, relatives, col...",Yes,NaN,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,2,11-15,300-399,3.75,0
14,No,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,1,4-7,< 200,3.25,0
15,Yes,2.0,The university aided me in obtaining the inter...,No,NaN,NaN,NaN,NaN,NaN,NaN,8-10,0,3.75,0
16,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,11-15,0,3.75,0
17,No,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",No,0,0-3,0,3.25,0
18,No,NaN,NaN,NaN,Yes,NaN,NaN,Applying to job postings,Yes,1,0-3,0,3.75,0
19,No,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",No,0,8-10,< 200,2.70,0
20,NaN,4.0,The university aided me in obtaining the inter...,Yes,NaN,Yes,The university aided me in obtaining the inter...,"Personal connections (teachers, relatives, col...",Yes,> 6,0-3,0,4.10,1
21,Yes,2.0,The university aided me in obtaining the inter...,Yes,NaN,NaN,NaN,Applying to job postings,Yes,> 6,0-3,400-499,2.70,0
22,No,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,1,20+,> 700,3.25,0
23,No,NaN,NaN,NaN,Yes,NaN,NaN,"Applying to job postings, Networking events",Yes,2,0-3,< 200,3.25,0
24,NaN,2.0,The university aided me in obtaining the inter...,No,NaN,Yes,The university aided me in obtaining the inter...,NaN,NaN,NaN,20+,200-299,3.75,1
25,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,16-20,> 700,3.75,0
26,No,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",No,0,8-10,< 200,2.70,0
27,No,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",No,0,4-7,0,3.25,0
28,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,0-3,600-699,3.25,0
29,Yes,1.0,"Personal connections (teachers, relatives, col...",Yes,NaN,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,1,4-7,200-299,3.75,0
30,Yes,1.0,Applications to job postings,No,NaN,NaN,NaN,NaN,NaN,NaN,20+,< 200,4.10,0
31,NaN,3.0,The university aided me in obtaining the inter...,No,NaN,Yes,The university aided me in obtaining the inter...,NaN,NaN,NaN,8-10,0,3.25,1
32,Yes,3.0,"Personal connections (teachers, relatives, col...",No,NaN,NaN,NaN,NaN,NaN,NaN,4-7,600-699,3.75,0
33,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,8-10,< 200,3.75,0
34,No,NaN,NaN,NaN,Yes,NaN,NaN,I have not yet began my search,No,0,11-15,< 200,2.70,0
35,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,0-3,< 200,3.75,0
36,NaN,2.0,The university aided me in obtaining the inter...,No,NaN,Yes,The university aided me in obtaining the inter...,NaN,NaN,NaN,0-3,500-599,3.25,1
37,NaN,NaN,NaN,NaN,NaN,No,The university aided me in obtaining the inter...,"Personal connections (teachers, relatives, col...",Yes,3,4-7,200-299,3.25,1
38,NaN,0.0,The university aided me in obtaining the inter...,No,NaN,Yes,The university aided me in obtaining the inter...,NaN,NaN,NaN,0-3,300-399,3.25,1
39,Yes,1.0,"Personal connections (teachers, relatives, col...",Yes,NaN,NaN,NaN,"Personal connections (teachers, relatives, col...",No,2,8-10,< 200,2.70,0
40,No,NaN,NaN,NaN,Yes,NaN,NaN,"Applying to job postings, Networking events",Yes,4,8-10,< 200,3.25,0
41,No,NaN,NaN,NaN,Yes,NaN,NaN,"Applying to job postings, Networking events",Yes,4,11-15,< 200,3.25,0
42,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,0-3,< 200,2.70,0
43,No,NaN,NaN,NaN,Yes,NaN,NaN,Networking events,Yes,2,11-15,< 200,3.25,0
44,NaN,2.0,The university aided me in obtaining the inter...,Yes,NaN,Yes,Applications to job postings,"Applying to job postings, Networking events",Yes,4,0-3,< 200,3.25,1
45,Yes,2.0,Applications to job postings,Yes,NaN,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,> 6,11-15,200-299,3.75,0
46,No,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,2,4-7,< 200,3.75,0
47,NaN,3.0,The university aided me in obtaining the inter...,No,NaN,Yes,The university aided me in obtaining the inter...,NaN,NaN,NaN,0-3,< 200,3.25,1
48,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,8-10,0,3.25,0
49,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,8-10,< 200,2.25,0
50,No,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,0-3,0,2.70,0
51,No,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,2,4-7,< 200,2.70,0
52,No,NaN,NaN,NaN,Yes,NaN,NaN,"Applying to job postings, Networking events",No,0,0-3,< 200,3.25,0
53,Yes,3.0,Applications to job postings,No,NaN,NaN,NaN,NaN,NaN,NaN,0-3,200-299,3.75,0
54,No,NaN,NaN,NaN,Yes,NaN,NaN,"Applying to job postings, Networking events",No,0,0-3,< 200,3.75,0

In [567]:
df = df.drop(columns = 'Have you ever completed an internship related to your program?')

In [568]:
df

,How many internships have you completed related to your program?,How have you obtained any of your internships?,Are you currently looking for an internship?,Are you currently looking for an internship or have in the past looked for an internship?,"Being in CO-OP, are you in the process or have you completed an internship related to your program?","Being in CO-OP, how do you go about finding an internship opportunity?",Which of the following describe how you've been searching for internships?,Have you ever gotten to an interview stage in the process of applying to an internship,If so how many interviews have you done in the process of applying for an internship,How often do you practice your program's material outside class related assignments? (In hours per week),"If you use it, how many connections do you have on LinkedIn?",GPA Midpoint,COOP
0,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,0-3,< 200,3.75,0
1,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,0-3,< 200,2.70,0
2,NaN,NaN,NaN,NaN,No,Applications to job postings,NaN,NaN,NaN,8-10,< 200,3.25,1
3,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,5,16-20,> 700,3.75,0
4,NaN,NaN,NaN,NaN,Yes,"Personal connections (teachers, relatives, col...",NaN,NaN,NaN,16-20,300-399,4.10,1
5,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",No,0,4-7,< 200,2.70,0
6,1.0,"Personal connections (teachers, relatives, col...",Yes,NaN,NaN,NaN,"Personal connections (teachers, relatives, col...",No,0,4-7,500-599,3.75,0
7,NaN,NaN,NaN,NaN,Yes,"Personal connections (teachers, relatives, col...",NaN,NaN,NaN,4-7,< 200,3.75,1
8,2.0,The university aided me in obtaining the inter...,No,NaN,Yes,The university aided me in obtaining the inter...,NaN,NaN,NaN,8-10,400-499,3.75,1
9,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,0-3,0,3.25,0
10,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,1,0-3,< 200,3.25,0
11,NaN,NaN,NaN,Yes,NaN,NaN,Doing research,No,0,4-7,500-599,3.25,0
12,1.0,"Personal connections (teachers, relatives, col...",No,NaN,NaN,NaN,NaN,NaN,NaN,11-15,200-299,3.75,0
13,1.0,"Personal connections (teachers, relatives, col...",Yes,NaN,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,2,11-15,300-399,3.75,0
14,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,1,4-7,< 200,3.25,0
15,2.0,The university aided me in obtaining the inter...,No,NaN,NaN,NaN,NaN,NaN,NaN,8-10,0,3.75,0
16,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,11-15,0,3.75,0
17,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",No,0,0-3,0,3.25,0
18,NaN,NaN,NaN,Yes,NaN,NaN,Applying to job postings,Yes,1,0-3,0,3.75,0
19,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",No,0,8-10,< 200,2.70,0
20,4.0,The university aided me in obtaining the inter...,Yes,NaN,Yes,The university aided me in obtaining the inter...,"Personal connections (teachers, relatives, col...",Yes,> 6,0-3,0,4.10,1
21,2.0,The university aided me in obtaining the inter...,Yes,NaN,NaN,NaN,Applying to job postings,Yes,> 6,0-3,400-499,2.70,0
22,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,1,20+,> 700,3.25,0
23,NaN,NaN,NaN,Yes,NaN,NaN,"Applying to job postings, Networking events",Yes,2,0-3,< 200,3.25,0
24,2.0,The university aided me in obtaining the inter...,No,NaN,Yes,The university aided me in obtaining the inter...,NaN,NaN,NaN,20+,200-299,3.75,1
25,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,16-20,> 700,3.75,0
26,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",No,0,8-10,< 200,2.70,0
27,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",No,0,4-7,0,3.25,0
28,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,0-3,600-699,3.25,0
29,1.0,"Personal connections (teachers, relatives, col...",Yes,NaN,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,1,4-7,200-299,3.75,0
30,1.0,Applications to job postings,No,NaN,NaN,NaN,NaN,NaN,NaN,20+,< 200,4.10,0
31,3.0,The university aided me in obtaining the inter...,No,NaN,Yes,The university aided me in obtaining the inter...,NaN,NaN,NaN,8-10,0,3.25,1
32,3.0,"Personal connections (teachers, relatives, col...",No,NaN,NaN,NaN,NaN,NaN,NaN,4-7,600-699,3.75,0
33,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,8-10,< 200,3.75,0
34,NaN,NaN,NaN,Yes,NaN,NaN,I have not yet began my search,No,0,11-15,< 200,2.70,0
35,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,0-3,< 200,3.75,0
36,2.0,The university aided me in obtaining the inter...,No,NaN,Yes,The university aided me in obtaining the inter...,NaN,NaN,NaN,0-3,500-599,3.25,1
37,NaN,NaN,NaN,NaN,No,The university aided me in obtaining the inter...,"Personal connections (teachers, relatives, col...",Yes,3,4-7,200-299,3.25,1
38,0.0,The university aided me in obtaining the inter...,No,NaN,Yes,The university aided me in obtaining the inter...,NaN,NaN,NaN,0-3,300-399,3.25,1
39,1.0,"Personal connections (teachers, relatives, col...",Yes,NaN,NaN,NaN,"Personal connections (teachers, relatives, col...",No,2,8-10,< 200,2.70,0
40,NaN,NaN,NaN,Yes,NaN,NaN,"Applying to job postings, Networking events",Yes,4,8-10,< 200,3.25,0
41,NaN,NaN,NaN,Yes,NaN,NaN,"Applying to job postings, Networking events",Yes,4,11-15,< 200,3.25,0
42,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,0-3,< 200,2.70,0
43,NaN,NaN,NaN,Yes,NaN,NaN,Networking events,Yes,2,11-15,< 200,3.25,0
44,2.0,The university aided me in obtaining the inter...,Yes,NaN,Yes,Applications to job postings,"Applying to job postings, Networking events",Yes,4,0-3,< 200,3.25,1
45,2.0,Applications to job postings,Yes,NaN,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,> 6,11-15,200-299,3.75,0
46,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,2,4-7,< 200,3.75,0
47,3.0,The university aided me in obtaining the inter...,No,NaN,Yes,The university aided me in obtaining the inter...,NaN,NaN,NaN,0-3,< 200,3.25,1
48,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,8-10,0,3.25,0
49,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,8-10,< 200,2.25,0
50,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,0-3,0,2.70,0
51,NaN,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,2,4-7,< 200,2.70,0
52,NaN,NaN,NaN,Yes,NaN,NaN,"Applying to job postings, Networking events",No,0,0-3,< 200,3.25,0
53,3.0,Applications to job postings,No,NaN,NaN,NaN,NaN,NaN,NaN,0-3,200-299,3.75,0
54,NaN,NaN,NaN,Yes,NaN,NaN,"Applying to job postings, Networking events",No,0,0-3,< 200,3.75,0

In [569]:
df['Number of Internships'] = df['How many internships have you completed related to your program?'].fillna(0).astype(int)
df= df.drop(columns = 'How many internships have you completed related to your program?')

In [570]:
df

,How have you obtained any of your internships?,Are you currently looking for an internship?,Are you currently looking for an internship or have in the past looked for an internship?,"Being in CO-OP, are you in the process or have you completed an internship related to your program?","Being in CO-OP, how do you go about finding an internship opportunity?",Which of the following describe how you've been searching for internships?,Have you ever gotten to an interview stage in the process of applying to an internship,If so how many interviews have you done in the process of applying for an internship,How often do you practice your program's material outside class related assignments? (In hours per week),"If you use it, how many connections do you have on LinkedIn?",GPA Midpoint,COOP,Number of Internships
0,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,0-3,< 200,3.75,0,0
1,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,0-3,< 200,2.70,0,0
2,NaN,NaN,NaN,No,Applications to job postings,NaN,NaN,NaN,8-10,< 200,3.25,1,0
3,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,5,16-20,> 700,3.75,0,0
4,NaN,NaN,NaN,Yes,"Personal connections (teachers, relatives, col...",NaN,NaN,NaN,16-20,300-399,4.10,1,0
5,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",No,0,4-7,< 200,2.70,0,0
6,"Personal connections (teachers, relatives, col...",Yes,NaN,NaN,NaN,"Personal connections (teachers, relatives, col...",No,0,4-7,500-599,3.75,0,1
7,NaN,NaN,NaN,Yes,"Personal connections (teachers, relatives, col...",NaN,NaN,NaN,4-7,< 200,3.75,1,0
8,The university aided me in obtaining the inter...,No,NaN,Yes,The university aided me in obtaining the inter...,NaN,NaN,NaN,8-10,400-499,3.75,1,2
9,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,0-3,0,3.25,0,0
10,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,1,0-3,< 200,3.25,0,0
11,NaN,NaN,Yes,NaN,NaN,Doing research,No,0,4-7,500-599,3.25,0,0
12,"Personal connections (teachers, relatives, col...",No,NaN,NaN,NaN,NaN,NaN,NaN,11-15,200-299,3.75,0,1
13,"Personal connections (teachers, relatives, col...",Yes,NaN,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,2,11-15,300-399,3.75,0,1
14,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,1,4-7,< 200,3.25,0,0
15,The university aided me in obtaining the inter...,No,NaN,NaN,NaN,NaN,NaN,NaN,8-10,0,3.75,0,2
16,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,11-15,0,3.75,0,0
17,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",No,0,0-3,0,3.25,0,0
18,NaN,NaN,Yes,NaN,NaN,Applying to job postings,Yes,1,0-3,0,3.75,0,0
19,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",No,0,8-10,< 200,2.70,0,0
20,The university aided me in obtaining the inter...,Yes,NaN,Yes,The university aided me in obtaining the inter...,"Personal connections (teachers, relatives, col...",Yes,> 6,0-3,0,4.10,1,4
21,The university aided me in obtaining the inter...,Yes,NaN,NaN,NaN,Applying to job postings,Yes,> 6,0-3,400-499,2.70,0,2
22,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,1,20+,> 700,3.25,0,0
23,NaN,NaN,Yes,NaN,NaN,"Applying to job postings, Networking events",Yes,2,0-3,< 200,3.25,0,0
24,The university aided me in obtaining the inter...,No,NaN,Yes,The university aided me in obtaining the inter...,NaN,NaN,NaN,20+,200-299,3.75,1,2
25,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,16-20,> 700,3.75,0,0
26,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",No,0,8-10,< 200,2.70,0,0
27,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",No,0,4-7,0,3.25,0,0
28,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,0-3,600-699,3.25,0,0
29,"Personal connections (teachers, relatives, col...",Yes,NaN,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,1,4-7,200-299,3.75,0,1
30,Applications to job postings,No,NaN,NaN,NaN,NaN,NaN,NaN,20+,< 200,4.10,0,1
31,The university aided me in obtaining the inter...,No,NaN,Yes,The university aided me in obtaining the inter...,NaN,NaN,NaN,8-10,0,3.25,1,3
32,"Personal connections (teachers, relatives, col...",No,NaN,NaN,NaN,NaN,NaN,NaN,4-7,600-699,3.75,0,3
33,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,8-10,< 200,3.75,0,0
34,NaN,NaN,Yes,NaN,NaN,I have not yet began my search,No,0,11-15,< 200,2.70,0,0
35,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,0-3,< 200,3.75,0,0
36,The university aided me in obtaining the inter...,No,NaN,Yes,The university aided me in obtaining the inter...,NaN,NaN,NaN,0-3,500-599,3.25,1,2
37,NaN,NaN,NaN,No,The university aided me in obtaining the inter...,"Personal connections (teachers, relatives, col...",Yes,3,4-7,200-299,3.25,1,0
38,The university aided me in obtaining the inter...,No,NaN,Yes,The university aided me in obtaining the inter...,NaN,NaN,NaN,0-3,300-399,3.25,1,0
39,"Personal connections (teachers, relatives, col...",Yes,NaN,NaN,NaN,"Personal connections (teachers, relatives, col...",No,2,8-10,< 200,2.70,0,1
40,NaN,NaN,Yes,NaN,NaN,"Applying to job postings, Networking events",Yes,4,8-10,< 200,3.25,0,0
41,NaN,NaN,Yes,NaN,NaN,"Applying to job postings, Networking events",Yes,4,11-15,< 200,3.25,0,0
42,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,0-3,< 200,2.70,0,0
43,NaN,NaN,Yes,NaN,NaN,Networking events,Yes,2,11-15,< 200,3.25,0,0
44,The university aided me in obtaining the inter...,Yes,NaN,Yes,Applications to job postings,"Applying to job postings, Networking events",Yes,4,0-3,< 200,3.25,1,2
45,Applications to job postings,Yes,NaN,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,> 6,11-15,200-299,3.75,0,2
46,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,2,4-7,< 200,3.75,0,0
47,The university aided me in obtaining the inter...,No,NaN,Yes,The university aided me in obtaining the inter...,NaN,NaN,NaN,0-3,< 200,3.25,1,3
48,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,8-10,0,3.25,0,0
49,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,8-10,< 200,2.25,0,0
50,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,0-3,0,2.70,0,0
51,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,2,4-7,< 200,2.70,0,0
52,NaN,NaN,Yes,NaN,NaN,"Applying to job postings, Networking events",No,0,0-3,< 200,3.25,0,0
53,Applications to job postings,No,NaN,NaN,NaN,NaN,NaN,NaN,0-3,200-299,3.75,0,3
54,NaN,NaN,Yes,NaN,NaN,"Applying to job postings, Networking events",No,0,0-3,< 200,3.75,0,0

In [571]:
columns_to_combine = [
    "Being in CO-OP, how do you go about finding an internship opportunity?",
    "Which of the following describe how you've been searching for internships?",
    "How have you obtained any of your internships?"
]


combined_column = df[columns_to_combine].fillna("")
combined_column = (
    combined_column[columns_to_combine[0]] + ", " + combined_column[columns_to_combine[1]]
).str.strip(", ")


df["Combined"] = combined_column


valid_options = [
    "The university aided me in obtaining the internship",
    "Personal connections (teachers, relatives, colleagues, friends, etc)",
    "Applications to job postings",
]


for option in valid_options:
    df[option] = df["Combined"].apply(
        lambda x: 1 if pd.notna(x) and option in x else 0
    )

In [572]:
df

,How have you obtained any of your internships?,Are you currently looking for an internship?,Are you currently looking for an internship or have in the past looked for an internship?,"Being in CO-OP, are you in the process or have you completed an internship related to your program?","Being in CO-OP, how do you go about finding an internship opportunity?",Which of the following describe how you've been searching for internships?,Have you ever gotten to an interview stage in the process of applying to an internship,If so how many interviews have you done in the process of applying for an internship,How often do you practice your program's material outside class related assignments? (In hours per week),"If you use it, how many connections do you have on LinkedIn?",GPA Midpoint,COOP,Number of Internships,Combined,The university aided me in obtaining the internship,"Personal connections (teachers, relatives, colleagues, friends, etc)",Applications to job postings
0,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,0-3,< 200,3.75,0,0,,0,0,0
1,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,0-3,< 200,2.70,0,0,,0,0,0
2,NaN,NaN,NaN,No,Applications to job postings,NaN,NaN,NaN,8-10,< 200,3.25,1,0,Applications to job postings,0,0,1
3,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,5,16-20,> 700,3.75,0,0,"Personal connections (teachers, relatives, col...",0,1,0
4,NaN,NaN,NaN,Yes,"Personal connections (teachers, relatives, col...",NaN,NaN,NaN,16-20,300-399,4.10,1,0,"Personal connections (teachers, relatives, col...",0,1,1
5,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",No,0,4-7,< 200,2.70,0,0,"Personal connections (teachers, relatives, col...",0,1,0
6,"Personal connections (teachers, relatives, col...",Yes,NaN,NaN,NaN,"Personal connections (teachers, relatives, col...",No,0,4-7,500-599,3.75,0,1,"Personal connections (teachers, relatives, col...",0,1,0
7,NaN,NaN,NaN,Yes,"Personal connections (teachers, relatives, col...",NaN,NaN,NaN,4-7,< 200,3.75,1,0,"Personal connections (teachers, relatives, col...",0,1,1
8,The university aided me in obtaining the inter...,No,NaN,Yes,The university aided me in obtaining the inter...,NaN,NaN,NaN,8-10,400-499,3.75,1,2,The university aided me in obtaining the inter...,1,1,1
9,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,0-3,0,3.25,0,0,,0,0,0
10,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,1,0-3,< 200,3.25,0,0,"Personal connections (teachers, relatives, col...",0,1,0
11,NaN,NaN,Yes,NaN,NaN,Doing research,No,0,4-7,500-599,3.25,0,0,Doing research,0,0,0
12,"Personal connections (teachers, relatives, col...",No,NaN,NaN,NaN,NaN,NaN,NaN,11-15,200-299,3.75,0,1,,0,0,0
13,"Personal connections (teachers, relatives, col...",Yes,NaN,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,2,11-15,300-399,3.75,0,1,"Personal connections (teachers, relatives, col...",0,1,0
14,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,1,4-7,< 200,3.25,0,0,"Personal connections (teachers, relatives, col...",0,1,0
15,The university aided me in obtaining the inter...,No,NaN,NaN,NaN,NaN,NaN,NaN,8-10,0,3.75,0,2,,0,0,0
16,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,11-15,0,3.75,0,0,,0,0,0
17,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",No,0,0-3,0,3.25,0,0,"Personal connections (teachers, relatives, col...",0,1,0
18,NaN,NaN,Yes,NaN,NaN,Applying to job postings,Yes,1,0-3,0,3.75,0,0,Applying to job postings,0,0,0
19,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",No,0,8-10,< 200,2.70,0,0,"Personal connections (teachers, relatives, col...",0,1,0
20,The university aided me in obtaining the inter...,Yes,NaN,Yes,The university aided me in obtaining the inter...,"Personal connections (teachers, relatives, col...",Yes,> 6,0-3,0,4.10,1,4,The university aided me in obtaining the inter...,1,1,1
21,The university aided me in obtaining the inter...,Yes,NaN,NaN,NaN,Applying to job postings,Yes,> 6,0-3,400-499,2.70,0,2,Applying to job postings,0,0,0
22,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,1,20+,> 700,3.25,0,0,"Personal connections (teachers, relatives, col...",0,1,0
23,NaN,NaN,Yes,NaN,NaN,"Applying to job postings, Networking events",Yes,2,0-3,< 200,3.25,0,0,"Applying to job postings, Networking events",0,0,0
24,The university aided me in obtaining the inter...,No,NaN,Yes,The university aided me in obtaining the inter...,NaN,NaN,NaN,20+,200-299,3.75,1,2,The university aided me in obtaining the inter...,1,0,0
25,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,16-20,> 700,3.75,0,0,,0,0,0
26,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",No,0,8-10,< 200,2.70,0,0,"Personal connections (teachers, relatives, col...",0,1,0
27,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",No,0,4-7,0,3.25,0,0,"Personal connections (teachers, relatives, col...",0,1,0
28,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,0-3,600-699,3.25,0,0,,0,0,0
29,"Personal connections (teachers, relatives, col...",Yes,NaN,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,1,4-7,200-299,3.75,0,1,"Personal connections (teachers, relatives, col...",0,1,0
30,Applications to job postings,No,NaN,NaN,NaN,NaN,NaN,NaN,20+,< 200,4.10,0,1,,0,0,0
31,The university aided me in obtaining the inter...,No,NaN,Yes,The university aided me in obtaining the inter...,NaN,NaN,NaN,8-10,0,3.25,1,3,The university aided me in obtaining the inter...,1,1,1
32,"Personal connections (teachers, relatives, col...",No,NaN,NaN,NaN,NaN,NaN,NaN,4-7,600-699,3.75,0,3,,0,0,0
33,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,8-10,< 200,3.75,0,0,,0,0,0
34,NaN,NaN,Yes,NaN,NaN,I have not yet began my search,No,0,11-15,< 200,2.70,0,0,I have not yet began my search,0,0,0
35,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,0-3,< 200,3.75,0,0,,0,0,0
36,The university aided me in obtaining the inter...,No,NaN,Yes,The university aided me in obtaining the inter...,NaN,NaN,NaN,0-3,500-599,3.25,1,2,The university aided me in obtaining the inter...,1,0,0
37,NaN,NaN,NaN,No,The university aided me in obtaining the inter...,"Personal connections (teachers, relatives, col...",Yes,3,4-7,200-299,3.25,1,0,The university aided me in obtaining the inter...,1,1,1
38,The university aided me in obtaining the inter...,No,NaN,Yes,The university aided me in obtaining the inter...,NaN,NaN,NaN,0-3,300-399,3.25,1,0,The university aided me in obtaining the inter...,1,0,1
39,"Personal connections (teachers, relatives, col...",Yes,NaN,NaN,NaN,"Personal connections (teachers, relatives, col...",No,2,8-10,< 200,2.70,0,1,"Personal connections (teachers, relatives, col...",0,1,0
40,NaN,NaN,Yes,NaN,NaN,"Applying to job postings, Networking events",Yes,4,8-10,< 200,3.25,0,0,"Applying to job postings, Networking events",0,0,0
41,NaN,NaN,Yes,NaN,NaN,"Applying to job postings, Networking events",Yes,4,11-15,< 200,3.25,0,0,"Applying to job postings, Networking events",0,0,0
42,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,0-3,< 200,2.70,0,0,,0,0,0
43,NaN,NaN,Yes,NaN,NaN,Networking events,Yes,2,11-15,< 200,3.25,0,0,Networking events,0,0,0
44,The university aided me in obtaining the inter...,Yes,NaN,Yes,Applications to job postings,"Applying to job postings, Networking events",Yes,4,0-3,< 200,3.25,1,2,"Applications to job postings, Applying to job ...",0,0,1
45,Applications to job postings,Yes,NaN,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,> 6,11-15,200-299,3.75,0,2,"Personal connections (teachers, relatives, col...",0,1,0
46,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,2,4-7,< 200,3.75,0,0,"Personal connections (teachers, relatives, col...",0,1,0
47,The university aided me in obtaining the inter...,No,NaN,Yes,The university aided me in obtaining the inter...,NaN,NaN,NaN,0-3,< 200,3.25,1,3,The university aided me in obtaining the inter...,1,0,0
48,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,8-10,0,3.25,0,0,,0,0,0
49,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,8-10,< 200,2.25,0,0,,0,0,0
50,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,0-3,0,2.70,0,0,,0,0,0
51,NaN,NaN,Yes,NaN,NaN,"Personal connections (teachers, relatives, col...",Yes,2,4-7,< 200,2.70,0,0,"Personal connections (teachers, relatives, col...",0,1,0
52,NaN,NaN,Yes,NaN,NaN,"Applying to job postings, Networking events",No,0,0-3,< 200,3.25,0,0,"Applying to job postings, Networking events",0,0,0
53,Applications to job postings,No,NaN,NaN,NaN,NaN,NaN,NaN,0-3,200-299,3.75,0,3,,0,0,0
54,NaN,NaN,Yes,NaN,NaN,"Applying to job postings, Networking events",No,0,0-3,< 200,3.75,0,0,"Applying to job postings, Networking events",0,0,0

In [573]:
df = df.drop(columns = "How have you obtained any of your internships?")
df = df.drop(columns = "Which of the following describe how you've been searching for internships?")
df = df.drop(columns = "Being in CO-OP, how do you go about finding an internship opportunity?")
df = df.drop(columns = "Combined")
df = df.drop(columns = "Are you currently looking for an internship or have in the past looked for an internship?")
df = df.drop(columns = "Are you currently looking for an internship?")
df = df.drop(columns = "Have you ever gotten to an interview stage in the process of applying to an internship")

In [574]:
interview_mapping = {
    '0': 0,
    '1': 1,
    '2': 2,
    '3': 3,
    '4': 4,
    '5': 5,
    '> 6': 6
}

# Map the GPA values and handle NaN by filling it with 0
df['number of interviews'] = df['If so how many interviews have you done in the process of applying for an internship'].map(interview_mapping).fillna(0)

# Drop the original GPA column
df = df.drop(columns='If so how many interviews have you done in the process of applying for an internship')

In [575]:
df["Number of Internships"] = df.apply(
    lambda row: 1
    if (
        row["Being in CO-OP, are you in the process or have you completed an internship related to your program?"] == "Yes"
        and row["Number of Internships"] == 0
    )
    else row["Number of Internships"],
    axis=1,
)
df = df.drop(columns = "Being in CO-OP, are you in the process or have you completed an internship related to your program?")

In [576]:
df

,How often do you practice your program's material outside class related assignments? (In hours per week),"If you use it, how many connections do you have on LinkedIn?",GPA Midpoint,COOP,Number of Internships,The university aided me in obtaining the internship,"Personal connections (teachers, relatives, colleagues, friends, etc)",Applications to job postings,number of interviews
0,0-3,< 200,3.75,0,0,0,0,0,0.0
1,0-3,< 200,2.70,0,0,0,0,0,0.0
2,8-10,< 200,3.25,1,0,0,0,1,0.0
3,16-20,> 700,3.75,0,0,0,1,0,5.0
4,16-20,300-399,4.10,1,1,0,1,1,0.0
5,4-7,< 200,2.70,0,0,0,1,0,0.0
6,4-7,500-599,3.75,0,1,0,1,0,0.0
7,4-7,< 200,3.75,1,1,0,1,1,0.0
8,8-10,400-499,3.75,1,2,1,1,1,0.0
9,0-3,0,3.25,0,0,0,0,0,0.0
10,0-3,< 200,3.25,0,0,0,1,0,1.0
11,4-7,500-599,3.25,0,0,0,0,0,0.0
12,11-15,200-299,3.75,0,1,0,0,0,0.0
13,11-15,300-399,3.75,0,1,0,1,0,2.0
14,4-7,< 200,3.25,0,0,0,1,0,1.0
15,8-10,0,3.75,0,2,0,0,0,0.0
16,11-15,0,3.75,0,0,0,0,0,0.0
17,0-3,0,3.25,0,0,0,1,0,0.0
18,0-3,0,3.75,0,0,0,0,0,1.0
19,8-10,< 200,2.70,0,0,0,1,0,0.0
20,0-3,0,4.10,1,4,1,1,1,6.0
21,0-3,400-499,2.70,0,2,0,0,0,6.0
22,20+,> 700,3.25,0,0,0,1,0,1.0
23,0-3,< 200,3.25,0,0,0,0,0,2.0
24,20+,200-299,3.75,1,2,1,0,0,0.0
25,16-20,> 700,3.75,0,0,0,0,0,0.0
26,8-10,< 200,2.70,0,0,0,1,0,0.0
27,4-7,0,3.25,0,0,0,1,0,0.0
28,0-3,600-699,3.25,0,0,0,0,0,0.0
29,4-7,200-299,3.75,0,1,0,1,0,1.0
30,20+,< 200,4.10,0,1,0,0,0,0.0
31,8-10,0,3.25,1,3,1,1,1,0.0
32,4-7,600-699,3.75,0,3,0,0,0,0.0
33,8-10,< 200,3.75,0,0,0,0,0,0.0
34,11-15,< 200,2.70,0,0,0,0,0,0.0
35,0-3,< 200,3.75,0,0,0,0,0,0.0
36,0-3,500-599,3.25,1,2,1,0,0,0.0
37,4-7,200-299,3.25,1,0,1,1,1,3.0
38,0-3,300-399,3.25,1,1,1,0,1,0.0
39,8-10,< 200,2.70,0,1,0,1,0,2.0
40,8-10,< 200,3.25,0,0,0,0,0,4.0
41,11-15,< 200,3.25,0,0,0,0,0,4.0
42,0-3,< 200,2.70,0,0,0,0,0,0.0
43,11-15,< 200,3.25,0,0,0,0,0,2.0
44,0-3,< 200,3.25,1,2,0,0,1,4.0
45,11-15,200-299,3.75,0,2,0,1,0,6.0
46,4-7,< 200,3.75,0,0,0,1,0,2.0
47,0-3,< 200,3.25,1,3,1,0,0,0.0
48,8-10,0,3.25,0,0,0,0,0,0.0
49,8-10,< 200,2.25,0,0,0,0,0,0.0
50,0-3,0,2.70,0,0,0,0,0,0.0
51,4-7,< 200,2.70,0,0,0,1,0,2.0
52,0-3,< 200,3.25,0,0,0,0,0,0.0
53,0-3,200-299,3.75,0,3,0,0,0,0.0
54,0-3,< 200,3.75,0,0,0,0,0,0.0

In [577]:
df

,How often do you practice your program's material outside class related assignments? (In hours per week),"If you use it, how many connections do you have on LinkedIn?",GPA Midpoint,COOP,Number of Internships,The university aided me in obtaining the internship,"Personal connections (teachers, relatives, colleagues, friends, etc)",Applications to job postings,number of interviews
0,0-3,< 200,3.75,0,0,0,0,0,0.0
1,0-3,< 200,2.70,0,0,0,0,0,0.0
2,8-10,< 200,3.25,1,0,0,0,1,0.0
3,16-20,> 700,3.75,0,0,0,1,0,5.0
4,16-20,300-399,4.10,1,1,0,1,1,0.0
5,4-7,< 200,2.70,0,0,0,1,0,0.0
6,4-7,500-599,3.75,0,1,0,1,0,0.0
7,4-7,< 200,3.75,1,1,0,1,1,0.0
8,8-10,400-499,3.75,1,2,1,1,1,0.0
9,0-3,0,3.25,0,0,0,0,0,0.0
10,0-3,< 200,3.25,0,0,0,1,0,1.0
11,4-7,500-599,3.25,0,0,0,0,0,0.0
12,11-15,200-299,3.75,0,1,0,0,0,0.0
13,11-15,300-399,3.75,0,1,0,1,0,2.0
14,4-7,< 200,3.25,0,0,0,1,0,1.0
15,8-10,0,3.75,0,2,0,0,0,0.0
16,11-15,0,3.75,0,0,0,0,0,0.0
17,0-3,0,3.25,0,0,0,1,0,0.0
18,0-3,0,3.75,0,0,0,0,0,1.0
19,8-10,< 200,2.70,0,0,0,1,0,0.0
20,0-3,0,4.10,1,4,1,1,1,6.0
21,0-3,400-499,2.70,0,2,0,0,0,6.0
22,20+,> 700,3.25,0,0,0,1,0,1.0
23,0-3,< 200,3.25,0,0,0,0,0,2.0
24,20+,200-299,3.75,1,2,1,0,0,0.0
25,16-20,> 700,3.75,0,0,0,0,0,0.0
26,8-10,< 200,2.70,0,0,0,1,0,0.0
27,4-7,0,3.25,0,0,0,1,0,0.0
28,0-3,600-699,3.25,0,0,0,0,0,0.0
29,4-7,200-299,3.75,0,1,0,1,0,1.0
30,20+,< 200,4.10,0,1,0,0,0,0.0
31,8-10,0,3.25,1,3,1,1,1,0.0
32,4-7,600-699,3.75,0,3,0,0,0,0.0
33,8-10,< 200,3.75,0,0,0,0,0,0.0
34,11-15,< 200,2.70,0,0,0,0,0,0.0
35,0-3,< 200,3.75,0,0,0,0,0,0.0
36,0-3,500-599,3.25,1,2,1,0,0,0.0
37,4-7,200-299,3.25,1,0,1,1,1,3.0
38,0-3,300-399,3.25,1,1,1,0,1,0.0
39,8-10,< 200,2.70,0,1,0,1,0,2.0
40,8-10,< 200,3.25,0,0,0,0,0,4.0
41,11-15,< 200,3.25,0,0,0,0,0,4.0
42,0-3,< 200,2.70,0,0,0,0,0,0.0
43,11-15,< 200,3.25,0,0,0,0,0,2.0
44,0-3,< 200,3.25,1,2,0,0,1,4.0
45,11-15,200-299,3.75,0,2,0,1,0,6.0
46,4-7,< 200,3.75,0,0,0,1,0,2.0
47,0-3,< 200,3.25,1,3,1,0,0,0.0
48,8-10,0,3.25,0,0,0,0,0,0.0
49,8-10,< 200,2.25,0,0,0,0,0,0.0
50,0-3,0,2.70,0,0,0,0,0,0.0
51,4-7,< 200,2.70,0,0,0,1,0,2.0
52,0-3,< 200,3.25,0,0,0,0,0,0.0
53,0-3,200-299,3.75,0,3,0,0,0,0.0
54,0-3,< 200,3.75,0,0,0,0,0,0.0

In [578]:
practice_mapping = {
    '0-3': 1.5,
    '4-7': 5.5,
    '8-10': 9,
    '11-15': 13,
    '16-20': 18,
    '20+': 23
}
df['Practice_Midpoint'] = df["How often do you practice your program's material outside class related assignments? (In hours per week)"].map(practice_mapping)
df = df.drop(columns = "How often do you practice your program's material outside class related assignments? (In hours per week)")

In [579]:
df

,"If you use it, how many connections do you have on LinkedIn?",GPA Midpoint,COOP,Number of Internships,The university aided me in obtaining the internship,"Personal connections (teachers, relatives, colleagues, friends, etc)",Applications to job postings,number of interviews,Practice_Midpoint
0,< 200,3.75,0,0,0,0,0,0.0,1.5
1,< 200,2.70,0,0,0,0,0,0.0,1.5
2,< 200,3.25,1,0,0,0,1,0.0,9.0
3,> 700,3.75,0,0,0,1,0,5.0,18.0
4,300-399,4.10,1,1,0,1,1,0.0,18.0
5,< 200,2.70,0,0,0,1,0,0.0,5.5
6,500-599,3.75,0,1,0,1,0,0.0,5.5
7,< 200,3.75,1,1,0,1,1,0.0,5.5
8,400-499,3.75,1,2,1,1,1,0.0,9.0
9,0,3.25,0,0,0,0,0,0.0,1.5
10,< 200,3.25,0,0,0,1,0,1.0,1.5
11,500-599,3.25,0,0,0,0,0,0.0,5.5
12,200-299,3.75,0,1,0,0,0,0.0,13.0
13,300-399,3.75,0,1,0,1,0,2.0,13.0
14,< 200,3.25,0,0,0,1,0,1.0,5.5
15,0,3.75,0,2,0,0,0,0.0,9.0
16,0,3.75,0,0,0,0,0,0.0,13.0
17,0,3.25,0,0,0,1,0,0.0,1.5
18,0,3.75,0,0,0,0,0,1.0,1.5
19,< 200,2.70,0,0,0,1,0,0.0,9.0
20,0,4.10,1,4,1,1,1,6.0,1.5
21,400-499,2.70,0,2,0,0,0,6.0,1.5
22,> 700,3.25,0,0,0,1,0,1.0,23.0
23,< 200,3.25,0,0,0,0,0,2.0,1.5
24,200-299,3.75,1,2,1,0,0,0.0,23.0
25,> 700,3.75,0,0,0,0,0,0.0,18.0
26,< 200,2.70,0,0,0,1,0,0.0,9.0
27,0,3.25,0,0,0,1,0,0.0,5.5
28,600-699,3.25,0,0,0,0,0,0.0,1.5
29,200-299,3.75,0,1,0,1,0,1.0,5.5
30,< 200,4.10,0,1,0,0,0,0.0,23.0
31,0,3.25,1,3,1,1,1,0.0,9.0
32,600-699,3.75,0,3,0,0,0,0.0,5.5
33,< 200,3.75,0,0,0,0,0,0.0,9.0
34,< 200,2.70,0,0,0,0,0,0.0,13.0
35,< 200,3.75,0,0,0,0,0,0.0,1.5
36,500-599,3.25,1,2,1,0,0,0.0,1.5
37,200-299,3.25,1,0,1,1,1,3.0,5.5
38,300-399,3.25,1,1,1,0,1,0.0,1.5
39,< 200,2.70,0,1,0,1,0,2.0,9.0
40,< 200,3.25,0,0,0,0,0,4.0,9.0
41,< 200,3.25,0,0,0,0,0,4.0,13.0
42,< 200,2.70,0,0,0,0,0,0.0,1.5
43,< 200,3.25,0,0,0,0,0,2.0,13.0
44,< 200,3.25,1,2,0,0,1,4.0,1.5
45,200-299,3.75,0,2,0,1,0,6.0,13.0
46,< 200,3.75,0,0,0,1,0,2.0,5.5
47,< 200,3.25,1,3,1,0,0,0.0,1.5
48,0,3.25,0,0,0,0,0,0.0,9.0
49,< 200,2.25,0,0,0,0,0,0.0,9.0
50,0,2.70,0,0,0,0,0,0.0,1.5
51,< 200,2.70,0,0,0,1,0,2.0,5.5
52,< 200,3.25,0,0,0,0,0,0.0,1.5
53,200-299,3.75,0,3,0,0,0,0.0,1.5
54,< 200,3.75,0,0,0,0,0,0.0,1.5

In [580]:
Linkedin_mapping = {
    '0': 0,
    '< 200': 100,
    '200-299': 250,
    '300-399': 350,
    '400-499': 450,
    '500-599': 550,
    '600-699':650,
    '> 700':750,
}
df['LinkedIn_Midpoint'] = df["If you use it, how many connections do you have on LinkedIn?"].map(Linkedin_mapping)
df = df.drop(columns = "If you use it, how many connections do you have on LinkedIn?")

In [581]:
df

,GPA Midpoint,COOP,Number of Internships,The university aided me in obtaining the internship,"Personal connections (teachers, relatives, colleagues, friends, etc)",Applications to job postings,number of interviews,Practice_Midpoint,LinkedIn_Midpoint
0,3.75,0,0,0,0,0,0.0,1.5,100
1,2.70,0,0,0,0,0,0.0,1.5,100
2,3.25,1,0,0,0,1,0.0,9.0,100
3,3.75,0,0,0,1,0,5.0,18.0,750
4,4.10,1,1,0,1,1,0.0,18.0,350
5,2.70,0,0,0,1,0,0.0,5.5,100
6,3.75,0,1,0,1,0,0.0,5.5,550
7,3.75,1,1,0,1,1,0.0,5.5,100
8,3.75,1,2,1,1,1,0.0,9.0,450
9,3.25,0,0,0,0,0,0.0,1.5,0
10,3.25,0,0,0,1,0,1.0,1.5,100
11,3.25,0,0,0,0,0,0.0,5.5,550
12,3.75,0,1,0,0,0,0.0,13.0,250
13,3.75,0,1,0,1,0,2.0,13.0,350
14,3.25,0,0,0,1,0,1.0,5.5,100
15,3.75,0,2,0,0,0,0.0,9.0,0
16,3.75,0,0,0,0,0,0.0,13.0,0
17,3.25,0,0,0,1,0,0.0,1.5,0
18,3.75,0,0,0,0,0,1.0,1.5,0
19,2.70,0,0,0,1,0,0.0,9.0,100
20,4.10,1,4,1,1,1,6.0,1.5,0
21,2.70,0,2,0,0,0,6.0,1.5,450
22,3.25,0,0,0,1,0,1.0,23.0,750
23,3.25,0,0,0,0,0,2.0,1.5,100
24,3.75,1,2,1,0,0,0.0,23.0,250
25,3.75,0,0,0,0,0,0.0,18.0,750
26,2.70,0,0,0,1,0,0.0,9.0,100
27,3.25,0,0,0,1,0,0.0,5.5,0
28,3.25,0,0,0,0,0,0.0,1.5,650
29,3.75,0,1,0,1,0,1.0,5.5,250
30,4.10,0,1,0,0,0,0.0,23.0,100
31,3.25,1,3,1,1,1,0.0,9.0,0
32,3.75,0,3,0,0,0,0.0,5.5,650
33,3.75,0,0,0,0,0,0.0,9.0,100
34,2.70,0,0,0,0,0,0.0,13.0,100
35,3.75,0,0,0,0,0,0.0,1.5,100
36,3.25,1,2,1,0,0,0.0,1.5,550
37,3.25,1,0,1,1,1,3.0,5.5,250
38,3.25,1,1,1,0,1,0.0,1.5,350
39,2.70,0,1,0,1,0,2.0,9.0,100
40,3.25,0,0,0,0,0,4.0,9.0,100
41,3.25,0,0,0,0,0,4.0,13.0,100
42,2.70,0,0,0,0,0,0.0,1.5,100
43,3.25,0,0,0,0,0,2.0,13.0,100
44,3.25,1,2,0,0,1,4.0,1.5,100
45,3.75,0,2,0,1,0,6.0,13.0,250
46,3.75,0,0,0,1,0,2.0,5.5,100
47,3.25,1,3,1,0,0,0.0,1.5,100
48,3.25,0,0,0,0,0,0.0,9.0,0
49,2.25,0,0,0,0,0,0.0,9.0,100
50,2.70,0,0,0,0,0,0.0,1.5,0
51,2.70,0,0,0,1,0,2.0,5.5,100
52,3.25,0,0,0,0,0,0.0,1.5,100
53,3.75,0,3,0,0,0,0.0,1.5,250
54,3.75,0,0,0,0,0,0.0,1.5,100

In [582]:
df["acquisition_rate"] = df.apply(
    lambda row: row["Number of Internships"] / row["number of interviews"]
    if row["number of interviews"] > 0
    else row["Number of Internships"],
    axis=1,
)

In [583]:
df

,GPA Midpoint,COOP,Number of Internships,The university aided me in obtaining the internship,"Personal connections (teachers, relatives, colleagues, friends, etc)",Applications to job postings,number of interviews,Practice_Midpoint,LinkedIn_Midpoint,acquisition_rate
0,3.75,0,0,0,0,0,0.0,1.5,100,0.000000
1,2.70,0,0,0,0,0,0.0,1.5,100,0.000000
2,3.25,1,0,0,0,1,0.0,9.0,100,0.000000
3,3.75,0,0,0,1,0,5.0,18.0,750,0.000000
4,4.10,1,1,0,1,1,0.0,18.0,350,1.000000
5,2.70,0,0,0,1,0,0.0,5.5,100,0.000000
6,3.75,0,1,0,1,0,0.0,5.5,550,1.000000
7,3.75,1,1,0,1,1,0.0,5.5,100,1.000000
8,3.75,1,2,1,1,1,0.0,9.0,450,2.000000
9,3.25,0,0,0,0,0,0.0,1.5,0,0.000000
10,3.25,0,0,0,1,0,1.0,1.5,100,0.000000
11,3.25,0,0,0,0,0,0.0,5.5,550,0.000000
12,3.75,0,1,0,0,0,0.0,13.0,250,1.000000
13,3.75,0,1,0,1,0,2.0,13.0,350,0.500000
14,3.25,0,0,0,1,0,1.0,5.5,100,0.000000
15,3.75,0,2,0,0,0,0.0,9.0,0,2.000000
16,3.75,0,0,0,0,0,0.0,13.0,0,0.000000
17,3.25,0,0,0,1,0,0.0,1.5,0,0.000000
18,3.75,0,0,0,0,0,1.0,1.5,0,0.000000
19,2.70,0,0,0,1,0,0.0,9.0,100,0.000000
20,4.10,1,4,1,1,1,6.0,1.5,0,0.666667
21,2.70,0,2,0,0,0,6.0,1.5,450,0.333333
22,3.25,0,0,0,1,0,1.0,23.0,750,0.000000
23,3.25,0,0,0,0,0,2.0,1.5,100,0.000000
24,3.75,1,2,1,0,0,0.0,23.0,250,2.000000
25,3.75,0,0,0,0,0,0.0,18.0,750,0.000000
26,2.70,0,0,0,1,0,0.0,9.0,100,0.000000
27,3.25,0,0,0,1,0,0.0,5.5,0,0.000000
28,3.25,0,0,0,0,0,0.0,1.5,650,0.000000
29,3.75,0,1,0,1,0,1.0,5.5,250,1.000000
30,4.10,0,1,0,0,0,0.0,23.0,100,1.000000
31,3.25,1,3,1,1,1,0.0,9.0,0,3.000000
32,3.75,0,3,0,0,0,0.0,5.5,650,3.000000
33,3.75,0,0,0,0,0,0.0,9.0,100,0.000000
34,2.70,0,0,0,0,0,0.0,13.0,100,0.000000
35,3.75,0,0,0,0,0,0.0,1.5,100,0.000000
36,3.25,1,2,1,0,0,0.0,1.5,550,2.000000
37,3.25,1,0,1,1,1,3.0,5.5,250,0.000000
38,3.25,1,1,1,0,1,0.0,1.5,350,1.000000
39,2.70,0,1,0,1,0,2.0,9.0,100,0.500000
40,3.25,0,0,0,0,0,4.0,9.0,100,0.000000
41,3.25,0,0,0,0,0,4.0,13.0,100,0.000000
42,2.70,0,0,0,0,0,0.0,1.5,100,0.000000
43,3.25,0,0,0,0,0,2.0,13.0,100,0.000000
44,3.25,1,2,0,0,1,4.0,1.5,100,0.500000
45,3.75,0,2,0,1,0,6.0,13.0,250,0.333333
46,3.75,0,0,0,1,0,2.0,5.5,100,0.000000
47,3.25,1,3,1,0,0,0.0,1.5,100,3.000000
48,3.25,0,0,0,0,0,0.0,9.0,0,0.000000
49,2.25,0,0,0,0,0,0.0,9.0,100,0.000000
50,2.70,0,0,0,0,0,0.0,1.5,0,0.000000
51,2.70,0,0,0,1,0,2.0,5.5,100,0.000000
52,3.25,0,0,0,0,0,0.0,1.5,100,0.000000
53,3.75,0,3,0,0,0,0.0,1.5,250,3.000000
54,3.75,0,0,0,0,0,0.0,1.5,100,0.000000

In [584]:
df.to_csv("processed_data.csv")